# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LunchLine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'

  # Pods for LunchLine

  target 'LunchLineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LunchLineUITests' do
    # Pods for testing
  end

end
